version: '2'

services:    
  straico_proxy:
    build: .
    ports: 
      - "3214:3214"
    restart: always
    environment:
      # example
      # - STRAICO_API_KEY=ko-111111111111111111111111111111111111111111111111
      - STRAICO_API_KEY=<... ADD YOUR STRAICO API KEY HERE >
 